INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Daniel', 'Huber', 'passwd', 'admin', 'admin', '2016-01-01 00:00:00')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('admin', 'ADMIN')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('admin', 'TRAINER')

INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Susi', 'Kaufgern', 'passwd', 'user1', 'admin', '2016-01-01 00:00:00')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('user1', 'PLAYER')

INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Max', 'Mustermann', 'passwd', 'user2', 'admin', '2016-01-01 00:00:00')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('user2', 'TRAINER')
INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'John', 'Doe', 'passwd', 'johndoe', 'admin', '2016-01-01 00:00:00')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('johndoe', 'ADMIN')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('johndoe', 'TRAINER')

INSERT INTO CLUB (NAME) VALUES('TC Wiesing')
INSERT INTO CLUB (NAME) VALUES('TC Vomp')

INSERT INTO TRAINING_GROUP (ID, BULLET_POINTS, COMMENT, COURT, DURATION_MINUTES, NUM_REMAINING_SESSIONS, REPLICATE_WEEKS, START_TIME, CLUB_NAME, TRAINER_USERNAME) VALUES(1, 'some bullet points', 'some comments', 'Court1', 60, 18, 18, '18:30', 'TC Wiesing', 'admin')
INSERT INTO TRAINING_GROUP (ID, BULLET_POINTS, COMMENT, COURT, DURATION_MINUTES, NUM_REMAINING_SESSIONS, REPLICATE_WEEKS, START_TIME, CLUB_NAME, TRAINER_USERNAME) VALUES(2, 'some bullet points', 'some comments', 'Court2', 60, 18, 18, '18:30', 'TC Vomp', 'admin')

